# Generated by Django 4.2 on 2023-04-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_rename_user_comment_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hashtag",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
