# Generated by Django 4.2 on 2023-04-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_post_hashtag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_displayed",
            field=models.BooleanField(default=True),
        ),
    ]
