# Generated by Django 4.2 on 2023-04-21 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userfollower",
            old_name="follower_id",
            new_name="follower",
        ),
        migrations.RenameField(
            model_name="userfollower",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterUniqueTogether(
            name="userfollower",
            unique_together={("user", "follower")},
        ),
    ]
